author: NightlySide
main: net.nightlyside.wg.regionhideplayer.WGRegionHidePlayers
version: '0.0.5'
name: WGRegionHidePlayers
load: POSTWORLD
description: "Hide player in specific WG region."
depend: [WorldGuard, WGCustomFlags]
commands:
  wgrhideplayers:
    description: Hide players
    usage: /<command> <on/off>
  hideprg:
    description: Hide players
    usage: /<command> <on/off>
permissions:
  wgrhideplayers.see:
    default: op
  wgrhideplayers.nohide:
    default: false